### PR TITLE
#618 English Translation of Tag lib and EL functions

### PR DESCRIPTION
**Pull request by attarudes**
#618  Sending pull request for merging to translation/5.0.0
Tag lib and EL functions has been translated.
Please review.

### CODE REVIEW

**Comment by kazuki43zoo** [comment]
- [ ] reflect https://github.com/terasolunaorg/guideline/pull/617/files#diff-90ee0d063e2d8ef037e1c9530550e271 in `ApplicationLayer.rst`

**Comment by kazuki43zoo** [comment]
@attarudes 

Thanks for translation !
Please rework this PR referring review comments.

**Comment by attarudes** [comment]
Understood.
Will modify the targed links in below rsts,
   source_en/ArchitectureInDetail/MessageManagement.rst 
   source_en/ArchitectureInDetail/Pagination.rst 
   source_en/ImplementationAtEachLayer/ApplicationLayer.rst 
   source_en/Security/XSS.rst

**Comment by attarudes** [comment]
Modification of targeted links are done.
Please review.

**Comment by btshimizukza** [comment]
@attarudes 

Thanks for translation.
I modified a small mistake
Please reflect(cherry-pick) to the master and 5.0.x.

**Pull request merged**
