### PR TITLE
Typo in SpringSecurityAuthorization.  #3053

### PR DESCRIPTION
**Pull request by btkyuuc**
Please review #3053 .

### CODE REVIEW

**Comment by yoshikawaa** [comment]
@btkyuuc 
I want you to do 2 actions.

* Confirm your git config ( user name, email ), and re-commit.
* Re-base branch on current master. (`git checkout master; git pull; git checkout [issue-branch]; git rebase master`)

**Comment by yoshikawaa** [comment]
@btkyuuc 
You must not cherry-pick commit. Please reset  and commit.
And when you fix it, please notify me that you want to review again with comments etc.

**Comment by btkyuuc** [comment]
@yoshikawaa 
I have reset and commit.
Please  review again.

**Comment by yoshikawaa** [comment]
@btkyuuc Thanks, but sorry required rebase current master for mergeing...

**Comment by btkyuuc** [comment]
@yoshikawaa
 I have rebased.
 Please review again.

**Comment by yoshikawaa** [comment]
@btkyuuc Thanks. Please also backport.

**Pull request merged**
