### PR TITLE
modified wrong discription of ValidationMessages.properties. #1948

### PR DESCRIPTION
**Pull request by btnoguchimnm**
Please review #1948 .

### CODE REVIEW

**Comment by btyoshikawaa** [comment]
@btnoguchimnm 
Sorry, I added a comment at #1948.
So when resolve that, I will review this again.

**Comment by btyoshikawaa** [comment]
@btnoguchimnm 
Please refer to https://github.com/terasolunaorg/guideline/issues/1948#issuecomment-233517115 and apply that.

**Comment by btnoguchimnm** [comment]
@btyoshikawaa 
I've rebased this branch.

**Comment by btyoshikawaa** [comment]
@btnoguchimnm 
Thanks to rapid response.

**Pull request merged**
