### PR TITLE
fixed description item no in spring-mvc-rest.xml(sample code). #2694

### PR DESCRIPTION
**Pull request by btmatsumotoms**
Please review #2694.

### CODE REVIEW

**Comment by kazuki43zoo** [comment]
@btmatsumotoms please re-base and fix english version.

**Comment by btmatsumotoms** [comment]
@yoshikawa Rebase is completed. and fix english version.

**Comment by yoshikawaa** [comment]
@btmatsumotoms 
Sorry, please rebase and push me.

**Comment by btmatsumotoms** [comment]
@yoshikawaa Rebase is completed.

**Comment by yoshikawaa** [comment]
@btmatsumotoms 
Please backport to 5.3.x .

**Pull request merged**
