### PR TITLE
updated infra and domain layer code #1323

### PR DESCRIPTION
**Pull request by attarudes**
Implemented in JP version only.
Once JP version is confirmed, accordingly will update English version too.
Request you to review #1323

### CODE REVIEW

**Comment by attarudes** [comment]
Review comment applied to JP version.

**Comment by attarudes** [comment]
Request you to review #1323

**Comment by attarudes** [comment]
Please review again #1323

**Comment by btshimizukza** [comment]
@attarudes 

I added one comment. Please check.

**Comment by attarudes** [comment]
Please review again #1323
Fixed the highlight portion problem.

**Comment by btshimizukza** [comment]
@attarudes Please backport 5.0.x.

**Pull request merged**
