### PR TITLE
fix some typos in DoubleSubmitProtection.rst #1411

### PR DESCRIPTION
**Pull request by garbagetown**
Please review #1411

### CODE REVIEW

**Comment by kazuki43zoo** [comment]
@garbagetown , thanks !

**Comment by btshimizukza** [comment]
@garbagetown Thanks for contributing!! If you contribute this project at next time, please include issue-number into commit message. 
For details, refer to [contributing guideline](https://github.com/terasolunaorg/guideline/blob/master/CONTRIBUTING.md).

Thanks.

**Comment by garbagetown** [comment]
@btshimizukza I see. I think this project is awesome, so I'll keep on contributing :-)

**Comment by btshimizukza** [comment]
@garbagetown We will welcome a your contributing !!

**Pull request merged**
